version: '3.2'

services:

    caddy:
        image: demo-registry.mancke.io/caddy
        ports:
            - 80:80 
            - 443:443
        volumes:
            - caddy-cfg:/root/.caddy            
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role != manager
                    
    content:
        image: demo-registry.mancke.io/content
        deploy:
            mode: replicated
            replicas: 2
            placement:
                constraints:
                    - node.role != manager

    wordpress:
        image: wordpress
        deploy:
            mode: replicated
            replicas: 2
            placement:
                constraints:
                    - node.role != manager

    static:
        image: nginx
        deploy:
            mode: replicated
            replicas: 2
            placement:
                constraints:
                    - node.role != manager

volumes:
    caddy-cfg: