version: '3.3'

services:
    registry:
        image: registry
        restart: always
        volumes:
            - registry:/var/lib/registry

    caddy:
        build: ./caddy
#        restart: always
        ports:
          - 80:80
          - 443:443
        volumes:
            - caddy-cfg:/root/.caddy

volumes:
    registry:
    caddy-cfg: